//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grafik_obecnosci
    {
        public int id_grafik { get; set; }
        public Nullable<int> id_pracownik { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public int id_status { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual Status_obecnosci Status_obecnosci { get; set; }
    }
}
