//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kalendarz_pracy
    {
        public int id_kalendarz_pracy { get; set; }
        public Nullable<int> id_kalendarz { get; set; }
        public Nullable<int> id_dzien_wolny_od_pracy { get; set; }
    
        public virtual Dzien_wolny_od_pracy Dzien_wolny_od_pracy { get; set; }
        public virtual Kalendarz_roku Kalendarz_roku { get; set; }
    }
}
