//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marza_zamowienie
    {
        public int id_marza_zamowienie { get; set; }
        public Nullable<int> id_zamowienie { get; set; }
        public Nullable<int> id_marza { get; set; }
    
        public virtual Marza Marza { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
    }
}
