//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maszyny()
        {
            this.Obslugi_maszyn = new HashSet<Obslugi_maszyn>();
            this.Produkcja_produktu = new HashSet<Produkcja_produktu>();
            this.Produkcja_elementu = new HashSet<Produkcja_elementu>();
            this.Wyposazenie_stanowiska_maszyny = new HashSet<Wyposazenie_stanowiska_maszyny>();
        }
    
        public int id_maszyny { get; set; }
        public string nazwa { get; set; }
        public int id_model { get; set; }
        public string numer_seryjny { get; set; }
        public System.DateTime data_produkcji { get; set; }
        public System.DateTime data_zakupu { get; set; }
        public Nullable<System.DateTime> data_wycofania { get; set; }
    
        public virtual Model_maszyny Model_maszyny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obslugi_maszyn> Obslugi_maszyn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_produktu> Produkcja_produktu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_elementu> Produkcja_elementu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyposazenie_stanowiska_maszyny> Wyposazenie_stanowiska_maszyny { get; set; }
    }
}
