//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Element_materialy = new HashSet<Element_materialy>();
            this.Szczegoly_zwrotu_z_produkcji = new HashSet<Szczegoly_zwrotu_z_produkcji>();
            this.Szczegoly_zaopatrzenia = new HashSet<Szczegoly_zaopatrzenia>();
            this.Szczegoly_wydania = new HashSet<Szczegoly_wydania>();
            this.Szczegoly_obslugi = new HashSet<Szczegoly_obslugi>();
            this.Wlasciwosci_materialu = new HashSet<Wlasciwosci_materialu>();
        }
    
        public int id_material { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> id_typ_mat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Element_materialy> Element_materialy { get; set; }
        public virtual Typ_materialu Typ_materialu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zwrotu_z_produkcji> Szczegoly_zwrotu_z_produkcji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zaopatrzenia> Szczegoly_zaopatrzenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_wydania> Szczegoly_wydania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_obslugi> Szczegoly_obslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wlasciwosci_materialu> Wlasciwosci_materialu { get; set; }
    }
}
