//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narzedzia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narzedzia()
        {
            this.Narzedzia_w_obsludze = new HashSet<Narzedzia_w_obsludze>();
            this.Szczegoly_zuzycia = new HashSet<Szczegoly_zuzycia>();
            this.Wlasciwosci_narzedzia = new HashSet<Wlasciwosci_narzedzia>();
            this.Wyposazenie_stanowiska_narzedzia = new HashSet<Wyposazenie_stanowiska_narzedzia>();
        }
    
        public int id_narzedzia { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> id_typ_narzedzia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narzedzia_w_obsludze> Narzedzia_w_obsludze { get; set; }
        public virtual Typ_narzedzia Typ_narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zuzycia> Szczegoly_zuzycia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wlasciwosci_narzedzia> Wlasciwosci_narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyposazenie_stanowiska_narzedzia> Wyposazenie_stanowiska_narzedzia { get; set; }
    }
}
