//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosc
    {
        public int id_platnosci { get; set; }
        public Nullable<int> id_statusu { get; set; }
        public Nullable<int> id_transakcji { get; set; }
        public Nullable<System.DateTime> data_platnosci { get; set; }
    
        public virtual Status_transakcji Status_transakcji { get; set; }
        public virtual Transakcje Transakcje { get; set; }
    }
}
