//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.Dostawa = new HashSet<Dostawa>();
            this.Grafik_obecnosci = new HashSet<Grafik_obecnosci>();
            this.Niedostepnosc = new HashSet<Niedostepnosc>();
            this.Obslugi_maszyn = new HashSet<Obslugi_maszyn>();
            this.Pensja = new HashSet<Pensja>();
            this.Pracownik_stanowiska = new HashSet<Pracownik_stanowiska>();
            this.Produkcja_produktu = new HashSet<Produkcja_produktu>();
            this.Produkcja_elementu = new HashSet<Produkcja_elementu>();
            this.Szczegoly_wyplata = new HashSet<Szczegoly_wyplata>();
            this.Szczegoly_zuzycia = new HashSet<Szczegoly_zuzycia>();
            this.Szczegoly_dostawa = new HashSet<Szczegoly_dostawa>();
            this.Szczegoly_zwrotu_z_produkcji = new HashSet<Szczegoly_zwrotu_z_produkcji>();
            this.Szczegoly_zaopatrzenia = new HashSet<Szczegoly_zaopatrzenia>();
            this.Szczegoly_wydania = new HashSet<Szczegoly_wydania>();
            this.Transport = new HashSet<Transport>();
            this.Urlop_pracownik = new HashSet<Urlop_pracownik>();
            this.Urlopy_nieobecnosc = new HashSet<Urlopy_nieobecnosc>();
            this.Wydanie_na_produkcje = new HashSet<Wydanie_na_produkcje>();
            this.Zamowienie = new HashSet<Zamowienie>();
            this.Zaopatrzenie = new HashSet<Zaopatrzenie>();
            this.Zwroty_z_produkcji = new HashSet<Zwroty_z_produkcji>();
        }
    
        public int id_pracownik { get; set; }
        public Nullable<int> id_osoba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostawa> Dostawa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grafik_obecnosci> Grafik_obecnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Niedostepnosc> Niedostepnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obslugi_maszyn> Obslugi_maszyn { get; set; }
        public virtual Osoba Osoba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pensja> Pensja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik_stanowiska> Pracownik_stanowiska { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_produktu> Produkcja_produktu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_elementu> Produkcja_elementu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_wyplata> Szczegoly_wyplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zuzycia> Szczegoly_zuzycia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_dostawa> Szczegoly_dostawa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zwrotu_z_produkcji> Szczegoly_zwrotu_z_produkcji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zaopatrzenia> Szczegoly_zaopatrzenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_wydania> Szczegoly_wydania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> Transport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urlop_pracownik> Urlop_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urlopy_nieobecnosc> Urlopy_nieobecnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wydanie_na_produkcje> Wydanie_na_produkcje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaopatrzenie> Zaopatrzenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwroty_z_produkcji> Zwroty_z_produkcji { get; set; }
    }
}
