//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt_elementy
    {
        public int id_produkt_elemetny { get; set; }
        public Nullable<int> id_produktu { get; set; }
        public Nullable<int> id_element { get; set; }
        public Nullable<int> ilosc_elementow_skladowych { get; set; }
        public Nullable<int> id_model { get; set; }
        public Nullable<int> id_parametry_maszyny { get; set; }
        public Nullable<decimal> czas_wytwarzania { get; set; }
    
        public virtual Element Element { get; set; }
        public virtual Model_maszyny Model_maszyny { get; set; }
        public virtual Produkt Produkt { get; set; }
        public virtual Szczegoly_parametry_maszyny Szczegoly_parametry_maszyny { get; set; }
    }
}
