//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stanowisko_produkcyjne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stanowisko_produkcyjne()
        {
            this.Produkcja_elementu = new HashSet<Produkcja_elementu>();
            this.Produkcja_produktu = new HashSet<Produkcja_produktu>();
            this.Stawka_RB = new HashSet<Stawka_RB>();
            this.Wyposazenie_stanowiska_narzedzia = new HashSet<Wyposazenie_stanowiska_narzedzia>();
            this.Wyposazenie_stanowiska_maszyny = new HashSet<Wyposazenie_stanowiska_maszyny>();
        }
    
        public int id_stanowisko_produkcyjne { get; set; }
        public Nullable<int> id_typ_stanowiska { get; set; }
        public string nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_elementu> Produkcja_elementu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_produktu> Produkcja_produktu { get; set; }
        public virtual Typ_stanowiska Typ_stanowiska { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stawka_RB> Stawka_RB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyposazenie_stanowiska_narzedzia> Wyposazenie_stanowiska_narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyposazenie_stanowiska_maszyny> Wyposazenie_stanowiska_maszyny { get; set; }
    }
}
