//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_parametry_maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Szczegoly_parametry_maszyny()
        {
            this.Element_materialy = new HashSet<Element_materialy>();
            this.Produkt_elementy = new HashSet<Produkt_elementy>();
        }
    
        public int id_parametry_maszyny { get; set; }
        public Nullable<int> id_rodzaj_wlasciwosci { get; set; }
        public string nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Element_materialy> Element_materialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkt_elementy> Produkt_elementy { get; set; }
        public virtual Rodzaj_wlasciwosci Rodzaj_wlasciwosci { get; set; }
    }
}
