//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_obslugi
    {
        public int id_szczegoly_obslugi { get; set; }
        public int id_obslugi { get; set; }
        public int id_material { get; set; }
        public string ilosc_mat { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Obslugi_maszyn Obslugi_maszyn { get; set; }
    }
}
