//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_wyplata
    {
        public int id_szczegoly_wyplata { get; set; }
        public Nullable<int> id_pracownik { get; set; }
        public Nullable<int> id_uprawnienia { get; set; }
        public System.DateTime data_wyplaty { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual Uprawnienia Uprawnienia { get; set; }
    }
}
