//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transport()
        {
            this.Szczegoly_dostawa = new HashSet<Szczegoly_dostawa>();
        }
    
        public int id_transport { get; set; }
        public Nullable<int> id_pracownik { get; set; }
        public Nullable<int> id_pojazdu { get; set; }
        public string stan_licznika_poczatek { get; set; }
        public string stan_licznika_koniec { get; set; }
    
        public virtual Pojazd Pojazd { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_dostawa> Szczegoly_dostawa { get; set; }
    }
}
