//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CenaWytworzeniaProduktowDoZamowieniaPosrednia
    {
        public int id_zamowienie { get; set; }
        public Nullable<int> id_produktu { get; set; }
        public string nazwa { get; set; }
        public Nullable<decimal> Czas_prdukcji_prodoktow { get; set; }
        public decimal Godzinowy_koszt_pracy_stanowiska { get; set; }
        public Nullable<decimal> Koszt_2 { get; set; }
    }
}
