//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CenaZaSztukeMaterialu
    {
        public string nazwa { get; set; }
        public int id_material { get; set; }
        public Nullable<int> id_zaopatrzenia { get; set; }
        public Nullable<decimal> cena_z { get; set; }
        public Nullable<decimal> ilosc_zaopatrzenia { get; set; }
        public Nullable<System.DateTime> data_przyjazdu { get; set; }
        public Nullable<decimal> Cena_za_Sztuke { get; set; }
    }
}
