//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CenaMaterialow1
    {
        public int id_zamowienie { get; set; }
        public int id_material { get; set; }
        public string nazwa_mat { get; set; }
        public Nullable<decimal> Cena_za_Sztuke { get; set; }
        public Nullable<decimal> suma_materialu { get; set; }
        public Nullable<decimal> Cena_dany_material { get; set; }
    }
}
