//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CzasRealizacjiZamowienia
    {
        public int Numer_zamowienia { get; set; }
        public string Status_realizacji { get; set; }
        public Nullable<int> Czas_trwania__dni_ { get; set; }
        public Nullable<int> Pozostale_dni_na_wykonanie_zlecenia { get; set; }
    }
}
