//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IloscElementowNaProdukt
    {
        public int id_produktu { get; set; }
        public string nazwa_produkt { get; set; }
        public int id_element { get; set; }
        public string nazwa_element { get; set; }
        public Nullable<int> ilosc { get; set; }
    }
}
