//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KalendarzDniPracujacych
    {
        public int rok { get; set; }
        public System.DateTime data_dnia_wolnego { get; set; }
        public string nazwa { get; set; }
    }
}
