//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Kosztytransportuklientow
    {
        public int id_klient { get; set; }
        public string Imie_i_nazwisko_klienta { get; set; }
        public int Numer_zamowienia { get; set; }
        public int id_pojazdu { get; set; }
        public string stan_licznika_poczatek { get; set; }
        public string stan_licznika_koniec { get; set; }
        public Nullable<int> Liczba_kilometrow { get; set; }
        public Nullable<decimal> stawka_za_kilometr { get; set; }
        public Nullable<decimal> Koszt_transportu__PLN_ { get; set; }
    }
}
