//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NieobecnosciPracownikaWMiesiacu
    {
        public Nullable<int> Rok { get; set; }
        public Nullable<int> Miesiąc { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int id_pracownik { get; set; }
        public Nullable<int> Liczba_dni_nieobecnosci { get; set; }
    }
}
