//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NiedostepnoscPracownika
    {
        public int id_pracownik { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string stan_pracownika { get; set; }
        public System.DateTime data_pierwszej_niedostepnosci { get; set; }
        public System.DateTime data_ostatniej_niedostepnosci { get; set; }
        public int niedostepnosc_pracownika { get; set; }
    }
}
