//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OstatniaDostawaDoKlienta
    {
        public int Numer_zamowienia { get; set; }
        public Nullable<System.DateTime> data_zlozenia { get; set; }
        public string nazwisko { get; set; }
        public string miasto { get; set; }
        public string kod_pocztowy { get; set; }
        public Nullable<int> lączna_ilosc_zamowionych_produktow { get; set; }
        public int Dostarczone_produkty { get; set; }
        public Nullable<int> Pozostalo_do_dostarczenia { get; set; }
        public Nullable<int> Pozostale_dni_na_dowiezienie { get; set; }
        public Nullable<decimal> sr__czas_realizacji_transportu__godzin_ { get; set; }
        public Nullable<decimal> sr__liczba_km_z_transportu { get; set; }
    }
}
