//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RbStanowiskoModel
    {
        public int id_stanowisko_produkcyjne { get; set; }
        public string nazwa { get; set; }
        public decimal Godzinowy_koszt_pracy_stanowiska { get; set; }
        public int id_model { get; set; }
    }
}
