//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StanMagazynowyPodsumowanie
    {
        public string nazwa_materialu { get; set; }
        public string typ_materialu { get; set; }
        public decimal ilosc_dostarczona_calkowita { get; set; }
        public int ilosc_wydana_calkowita { get; set; }
        public int ilosc_zwrocona_calkowita { get; set; }
        public Nullable<decimal> bilans_magazynowy { get; set; }
    }
}
