//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StanMaszyn
    {
        public int Numer_identyfikacji_maszyny { get; set; }
        public string Nazwa_maszyny { get; set; }
        public string Numer_seryjny { get; set; }
        public string Stanowisko_produkcyjne { get; set; }
        public string Stan { get; set; }
    }
}
