//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WplywySumaPerKlient
    {
        public int id_klient { get; set; }
        public string imie_nazwisko_klienta { get; set; }
        public Nullable<decimal> suma_transport { get; set; }
        public Nullable<decimal> suma_zamowienia { get; set; }
        public Nullable<decimal> suma_laczna { get; set; }
    }
}
