//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WydatkiSuma
    {
        public Nullable<int> Rok { get; set; }
        public Nullable<int> Miesiac { get; set; }
        public double Suma_wynagrodzen_po_potraceniu { get; set; }
        public decimal Suma_kosztow_materialow { get; set; }
        public Nullable<double> Laczne_wydatki { get; set; }
    }
}
