//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WyszukajPoStanowisku
    {
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string nazwa { get; set; }
        public System.DateTime data_zatrudnienia { get; set; }
        public Nullable<System.DateTime> data_zwolnienia { get; set; }
    }
}
