//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WynagrodzeniePracownika
    {
        public Nullable<int> id_pracownik { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public System.DateTime Data_wyplaty { get; set; }
        public Nullable<decimal> Podstawa_wynagrodzenia { get; set; }
        public int Dni_do_potrącenia { get; set; }
        public decimal Suma_dodatkow { get; set; }
        public Nullable<decimal> Wynagrodzenie_brutto { get; set; }
        public double Kwota_potrącenia { get; set; }
        public Nullable<double> Wynagrodzenie_po_potrąceniu { get; set; }
    }
}
