//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WyprodukowaneProduktyDobre
    {
        public Nullable<int> id_zamowienie { get; set; }
        public int id_produkcja_produktu { get; set; }
        public Nullable<int> id_produktu { get; set; }
        public Nullable<int> id_czynnosc { get; set; }
        public Nullable<decimal> ilosc_dobrych { get; set; }
    }
}
