//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wlasciwosci_materialu
    {
        public int id_wlasciwosci_materialu { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> id_rodzaj_wlasciwosci { get; set; }
        public Nullable<decimal> wartosc_nom { get; set; }
        public Nullable<decimal> wartosc_min { get; set; }
        public Nullable<decimal> wartosc_max { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Rodzaj_wlasciwosci Rodzaj_wlasciwosci { get; set; }
    }
}
