//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wlasciwosci_narzedzia
    {
        public int id_wlasciwosci_narzedzia { get; set; }
        public int id_narzedzia { get; set; }
        public int id_rodzaj_wlasciwosci { get; set; }
        public decimal wartosc_nom { get; set; }
        public decimal wartosc_min { get; set; }
        public decimal wartosc_max { get; set; }
    
        public virtual Narzedzia Narzedzia { get; set; }
        public virtual Rodzaj_wlasciwosci Rodzaj_wlasciwosci { get; set; }
    }
}
