//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element_materialy
    {
        public int id_elementy_material { get; set; }
        public Nullable<int> id_element { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> id_model { get; set; }
        public Nullable<int> id_parametry_maszyny { get; set; }
        public Nullable<decimal> czas_wytwarzania { get; set; }
    
        public virtual Element Element { get; set; }
        public virtual Material Material { get; set; }
        public virtual Model_maszyny Model_maszyny { get; set; }
        public virtual Szczegoly_parametry_maszyny Szczegoly_parametry_maszyny { get; set; }
    }
}
