//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narzedzia_w_obsludze
    {
        public int id_narzedzia_w_obsudze { get; set; }
        public Nullable<int> id_obslugi { get; set; }
        public int id_narzedzia { get; set; }
    
        public virtual Narzedzia Narzedzia { get; set; }
        public virtual Obslugi_maszyn Obslugi_maszyn { get; set; }
    }
}
