//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pojazd()
        {
            this.Przeglady_pojazdy = new HashSet<Przeglady_pojazdy>();
            this.Transport = new HashSet<Transport>();
            this.Ubezpieczenia_pojazdy = new HashSet<Ubezpieczenia_pojazdy>();
        }
    
        public int id_pojazdu { get; set; }
        public Nullable<int> id_typ_pojazdu { get; set; }
        public Nullable<int> id_model_pojazdu { get; set; }
        public string VIN { get; set; }
        public Nullable<decimal> stawka_za_kilometr { get; set; }
        public Nullable<System.DateTime> data_zakupu { get; set; }
        public Nullable<System.DateTime> data_zdjecia_ze_stanu { get; set; }
    
        public virtual Model_pojazdu Model_pojazdu { get; set; }
        public virtual Typ_pojazdu Typ_pojazdu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przeglady_pojazdy> Przeglady_pojazdy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> Transport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ubezpieczenia_pojazdy> Ubezpieczenia_pojazdy { get; set; }
    }
}
