//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik_stanowiska
    {
        public int id_pracownik_stanowiska { get; set; }
        public Nullable<int> id_pracownik { get; set; }
        public Nullable<int> id_stanowisko { get; set; }
        public System.DateTime data_zatrudnienia { get; set; }
        public Nullable<System.DateTime> data_zwolnienia { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual Stanowisko Stanowisko { get; set; }
    }
}
