//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przeglady_pojazdy
    {
        public int id_przegladu { get; set; }
        public Nullable<int> id_pojazdu { get; set; }
        public Nullable<System.DateTime> data_przegladu { get; set; }
        public Nullable<System.DateTime> data_kolejnego_przegladu { get; set; }
    
        public virtual Pojazd Pojazd { get; set; }
    }
}
