//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_zuzycia
    {
        public int id_szczegoly_zuzycia { get; set; }
        public int id_narzedzia { get; set; }
        public System.DateTime data_zuzycia { get; set; }
        public Nullable<int> id_pracownik { get; set; }
    
        public virtual Narzedzia Narzedzia { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
