//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_zwrotu_z_produkcji
    {
        public int id_szczegoly_zwrtou_z_produkcji { get; set; }
        public Nullable<int> id_zwrotu { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> ilosc { get; set; }
        public Nullable<System.DateTime> data_zwrotu { get; set; }
        public Nullable<int> id_pracownik { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Zwroty_z_produkcji Zwroty_z_produkcji { get; set; }
    }
}
