//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_zaopatrzenia
    {
        public int id_szczegoly_zaopatrzenia { get; set; }
        public Nullable<int> id_zaopatrzenia { get; set; }
        public Nullable<int> id_materialu { get; set; }
        public Nullable<decimal> ilosc_zaopatrzenia { get; set; }
        public Nullable<decimal> cena_z { get; set; }
        public Nullable<System.DateTime> data_przyjazdu { get; set; }
        public Nullable<int> id_pracownik { get; set; }
        public string numer_certyfikatu { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Zaopatrzenie Zaopatrzenie { get; set; }
    }
}
