//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_wydatku
    {
        public int id_szczegoly_wydatku { get; set; }
        public Nullable<int> id_typ_wydatku { get; set; }
        public Nullable<int> id_cechy_wydatku { get; set; }
    
        public virtual Cecha_wydatku Cecha_wydatku { get; set; }
        public virtual Typ_wydatku Typ_wydatku { get; set; }
    }
}
