//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_wydania
    {
        public int id_szczegoly_wydania { get; set; }
        public Nullable<int> id_wydania { get; set; }
        public Nullable<int> id_materialu { get; set; }
        public Nullable<int> ilosc { get; set; }
        public System.DateTime data_wydania { get; set; }
        public Nullable<int> id_pracownik { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Wydanie_na_produkcje Wydanie_na_produkcje { get; set; }
    }
}
