//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_dostawa
    {
        public int id_szczegoly_dostawa { get; set; }
        public Nullable<int> id_dostawy { get; set; }
        public Nullable<int> id_produktu { get; set; }
        public Nullable<int> ilosc { get; set; }
        public Nullable<System.DateTime> data_przyjazdu { get; set; }
        public Nullable<int> id_pracownik { get; set; }
        public Nullable<int> id_transport { get; set; }
        public string numer_certyfikatu { get; set; }
    
        public virtual Dostawa Dostawa { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Produkt Produkt { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
