//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AktualneStawkiRbStanowiska
    {
        public int id_stwaka_rb { get; set; }
        public int id_stanowisko_produkcyjne { get; set; }
        public System.DateTime data_poczatek { get; set; }
        public Nullable<System.DateTime> data_koniec { get; set; }
        public decimal Godzinowy_koszt_pracy_stanowiska { get; set; }
    }
}
