//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Bilans
    {
        public decimal suma_transport { get; set; }
        public decimal suma_zamowienia { get; set; }
        public decimal suma_wplywow { get; set; }
        public double suma_wydatkow { get; set; }
        public Nullable<double> bilans { get; set; }
    }
}
