//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ElementDlugosc
    {
        public int id_element { get; set; }
        public string nazwa_ele { get; set; }
        public Nullable<int> id_rodzaj_wlasciwosci { get; set; }
        public Nullable<decimal> dl_ele { get; set; }
    }
}
