//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IlosMaterialuDoZamowieniaPosrednia
    {
        public int id_zamowienie { get; set; }
        public Nullable<int> id_element { get; set; }
        public string nazwa_ele { get; set; }
        public Nullable<int> suma_ilosci { get; set; }
        public Nullable<int> id_material { get; set; }
        public string nazwa_mat { get; set; }
        public Nullable<decimal> ilosc_ele_na_mat { get; set; }
        public Nullable<decimal> Ilosc_materialu_do_zamowienia { get; set; }
    }
}
