//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KosztProdukcjaElementuDoZamowienia
    {
        public int id_zamowienie { get; set; }
        public Nullable<decimal> Koszt_produkcji_elementow { get; set; }
    }
}
