//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PozostalyUrlop
    {
        public Nullable<int> id_pracownik { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int przyznane_dni { get; set; }
        public int wykorzystane_dni { get; set; }
        public Nullable<int> pozostale_dni { get; set; }
    }
}
