//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProdukcjaProdukty
    {
        public int id_zamowienie { get; set; }
        public Nullable<int> id_czynnosc { get; set; }
        public Nullable<int> id_produktu { get; set; }
        public Nullable<int> ile_do_wyprodukowania_prodoktow { get; set; }
        public Nullable<decimal> ile_wyprodukowano_prodoktow { get; set; }
        public string Status_Realizacji { get; set; }
        public Nullable<decimal> Procent_realizacji { get; set; }
    }
}
