//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StanMagazynowyZwrot
    {
        public string nazwa_materialu { get; set; }
        public string typ_materialu { get; set; }
        public Nullable<int> id_zamowienie { get; set; }
        public Nullable<int> ilosc { get; set; }
        public string jednostka { get; set; }
        public Nullable<System.DateTime> data_zwrotu { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
    }
}
