//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Stan_uzytkowania_narzedzi
    {
        public int id_narzedzia { get; set; }
        public string nazwa_narzedzia { get; set; }
        public Nullable<System.DateTime> ostatnia_data_obslugi { get; set; }
        public Nullable<System.DateTime> data_zuzycia { get; set; }
        public string status { get; set; }
    }
}
