//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StanNarzedzi
    {
        public string Nazwa_Narzedzia { get; set; }
        public int ID_Obslugi { get; set; }
        public System.DateTime Data_Poczatek { get; set; }
        public System.DateTime Data_Koniec { get; set; }
        public string Nazwa_Maszyny { get; set; }
        public string Typ_Obslugi { get; set; }
    }
}
