//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WplywySumaPerZamowienie
    {
        public Nullable<int> Numer_zamowienia { get; set; }
        public decimal koszt_transportu { get; set; }
        public decimal koszt_zamowienia { get; set; }
        public Nullable<decimal> suma_laczna { get; set; }
    }
}
