//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WyprodukowaneElementyDobre
    {
        public Nullable<int> id_zamowienie { get; set; }
        public int id_produkcja_elementu { get; set; }
        public Nullable<int> id_element { get; set; }
        public Nullable<decimal> ilosc_dobrych { get; set; }
    }
}
