//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wlasciwosci_miar
    {
        public int id_wlasciwosci_miar { get; set; }
        public Nullable<int> id_miar { get; set; }
        public Nullable<int> id_rodzaj_wlasciwosci { get; set; }
    
        public virtual Miary Miary { get; set; }
        public virtual Rodzaj_wlasciwosci Rodzaj_wlasciwosci { get; set; }
    }
}
