//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wplywy
    {
        public int id_wplywy { get; set; }
        public Nullable<int> id_transakcji { get; set; }
        public Nullable<int> id_zamowienie { get; set; }
    
        public virtual Transakcje Transakcje { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
    }
}
