//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.Dostawa = new HashSet<Dostawa>();
            this.Marza_zamowienie = new HashSet<Marza_zamowienie>();
            this.Produkcja_elementu = new HashSet<Produkcja_elementu>();
            this.Produkcja_produktu = new HashSet<Produkcja_produktu>();
            this.Szczegoly_zamowienia = new HashSet<Szczegoly_zamowienia>();
            this.Transakcje = new HashSet<Transakcje>();
            this.Wplywy = new HashSet<Wplywy>();
            this.Wydanie_na_produkcje = new HashSet<Wydanie_na_produkcje>();
            this.Zwroty_z_produkcji = new HashSet<Zwroty_z_produkcji>();
        }
    
        public int id_zamowienie { get; set; }
        public Nullable<int> id_klient { get; set; }
        public Nullable<System.DateTime> data_zlozenia { get; set; }
        public Nullable<System.DateTime> data_planowanego_zakonczenia { get; set; }
        public Nullable<int> id_pracownik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostawa> Dostawa { get; set; }
        public virtual Klient Klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marza_zamowienie> Marza_zamowienie { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_elementu> Produkcja_elementu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkcja_produktu> Produkcja_produktu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zamowienia> Szczegoly_zamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcje> Transakcje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wplywy> Wplywy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wydanie_na_produkcje> Wydanie_na_produkcje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwroty_z_produkcji> Zwroty_z_produkcji { get; set; }
    }
}
